=== ircf/mapix/mapix/lang/messages.xsd
<?xml version="1.0"?>
<!-- Mapix Messages schema definition -->
<xsd:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mapixcms.org/schemas/schema.xsd">
	<!-- Messages attributes -->
	<xsd:attribute name="id" type="xsd:string" use="required"/>
	<xsd:attribute name="lang" type="xsd:string"/>
	<!-- Messages elements -->
	<xsd:element name="messages" minOccurs="1" maxOccurs="1" type="xsd:string">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				This document root contains messages in several languages for the whole site
			</xsd:documentation>
			<xsd:documentation xml:lang="fr">
				Ce document contient des messages dans différentes langues pour l'ensemble du site
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="message"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="message" minOccurs="1" maxOccurs="unbounded" type="xsd:string">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				A message is a sentence or a paragraph that can be used anywhere in the site,
				messages are usually used to handle global content and to avoid using static content in templates or programs
			</xsd:documentation>
			<xsd:documentation xml:lang="fr">
				Un message est une phrase ou un paragraphe pouvant être utilisé n'importe où sur le site,
				il est recommandé de les utiliser pour gérer les contenus globaux et pour éviter d'avoir à utiliser
				du contenu en dur dans les gabarits (templates) ou programmes.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute ref="id"/>
			<xsd:attribute ref="lang"/>
			<xsd:sequence>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== ircf/mapix/mapix/file/messages.xml
<?xml version="1.0"?>
<!-- Folder application messages -->
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mapixcms.org/schemas/messages.xsd">
	<message id="folderEditor" lang="en">Folder editor</message>
	<message id="folderEditor" lang="fr">Explorateur de fichiers</message>
	<message id="fileName" lang="en">File name</message>
	<message id="fileName" lang="fr">Nom du fichier</message>
	<message id="fileSize" lang="en">File size</message>
	<message id="fileSize" lang="fr">Taille du fichier</message>
	<message id="fileType" lang="en">File type</message>
	<message id="fileType" lang="fr">Type de fichier</message>
	<message id="dateCreated" lang="en">Date created</message>
	<message id="dateCreated" lang="fr">Date de création</message>
	<message id="dateModified" lang="en">Date modified</message>
	<message id="dateModified" lang="fr">Date de modification</message>
	<message id="createFile" lang="en">Create a new file</message>
	<message id="createFile" lang="fr">Nouveau fichier</message>
	<message id="textFile" lang="en">Text file</message>
	<message id="textFile" lang="fr">Fichier texte</message>
	<message id="xmlDocument" lang="en">XML Document</message>
	<message id="xmlDocument" lang="fr">Document XML</message>
	<message id="folder" lang="en">Folder</message>
	<message id="folder" lang="fr">Dossier</message>
	<message id="xmlSchema" lang="en">XML Schema</message>
	<message id="xmlSchema" lang="fr">Schema XML</message>
	<message id="copyFile" lang="en">Copy file</message>
	<message id="copyFile" lang="fr">Copier le fichier</message>
	<message id="sourceFile" lang="en">Source file</message>
	<message id="sourceFile" lang="fr">Fichier d'origine</message>
	<message id="targetFolder" lang="en">Target folder</message>
	<message id="targetFolder" lang="fr">Dossier de destination</message>
	<message id="targetFile" lang="en">Target file</message>
	<message id="targetFile" lang="fr">Fichier de destination</message>
	<message id="moveFile" lang="en">Move file</message>
	<message id="moveFile" lang="fr">Déplacer le fichier</message>
	<message id="deleteFile" lang="en">Delete file</message>
	<message id="deleteFile" lang="fr">Supprimer le fichier</message>
	<message id="uploadFiles" lang="en">Upload files</message>
	<message id="uploadFiles" lang="fr">Mettre des fichiers en ligne</message>
	<message id="uploadFile" lang="en">Upload a file</message>
	<message id="uploadFile" lang="fr">Mettre en ligne</message>
	<message id="close" lang="en">Close</message>
	<message id="close" lang="fr">Fermer</message>
	<message id="toggleViewMode" lang="en">Toggle view mode</message>
	<message id="toggleViewMode" lang="fr">Basculer affichage</message>
	<message id="toggleHiddenFiles" lang="en">Toggle hidden files</message>
	<message id="toggleHiddenFiles" lang="fr">Afficher/Cacher les fichiers cachés</message>
	<message id="extractArchive" lang="en">Extract archive</message>
	<message id="extractArchive" lang="fr">Extraire l'archive</message>
	<message id="deleteArchive" lang="en">Delete archive after extracting</message>
	<message id="deleteArchive" lang="fr">Supprimer l'archive après extraction</message>
	<message id="lockUnlock" lang="en">Lock / Unlock file</message>
	<message id="lockUnlock" lang="fr">Verrouiller / Déverrouiller</message>
	<message id="lock" lang="en">Lock</message>
	<message id="lock" lang="fr">Verrouiller</message>
	<message id="unlock" lang="en">Unlock</message>
	<message id="unlock" lang="fr">Déverrouiller</message>
	<message id="backupRestore" lang="en">Back up / Restore</message>
	<message id="backupRestore" lang="fr">Sauvegarder / Restaurer</message>
	<message id="backup" lang="en">Back up</message>
	<message id="backup" lang="fr">Sauvegarder</message>
	<message id="restore" lang="en">Restore</message>
	<message id="restore" lang="fr">Restaurer</message>
	<message id="created" lang="en">created</message>
	<message id="created" lang="fr">créé</message>
	<message id="deleted" lang="en">deleted</message>
	<message id="deleted" lang="fr">supprimé</message>
	<message id="uploaded" lang="en">uploaded</message>
	<message id="uploaded" lang="fr">mis en ligne</message>
	<message id="moved" lang="en">moved</message>
	<message id="moved" lang="fr">déplacé</message>
	<message id="copied" lang="en">copied</message>
	<message id="copied" lang="fr">copié</message>
	<message id="backedUp" lang="en">backed up</message>
	<message id="backedUp" lang="fr">sauvegardé</message>
	<message id="restored" lang="en">restored</message>
	<message id="restored" lang="fr">restauré</message>
	<message id="extracted" lang="en">extracted</message>
	<message id="extracted" lang="fr">extrait</message>
	<message id="folderError" lang="en">This file is not a folder. Try to open it with a different editor.</message>
	<message id="folderError" lang="fr">Ce fichier n'est pas un dossier. Essayez de l'ouvrir avec un autre éditeur.</message>
	<message id="displaySubcontent" lang="en">Display Subcontent</message>
	<message id="displaySubcontent" lang="fr">Afficher sous-menu</message>
	<message id="browseFiles" lang="en">Browse Files</message>
	<message id="browseFiles" lang="fr">Parcourir les fichiers</message>
	<message id="clearList" lang="en">Clear List</message>
	<message id="clearList" lang="fr">Effacer la liste</message>
	<message id="startUpload" lang="en">Start Upload</message>
	<message id="startUpload" lang="fr">Commencer le téléchargement</message>
	<message id="overallProgress" lang="en">Overall Progress</message>
	<message id="overallProgress" lang="fr">Progression globale</message>
	<message id="fileProgress" lang="en">File Progress</message>
	<message id="fileProgress" lang="fr">Progression d'un fichier</message>
</messages>

=== ircf/mapix/mapix/admin/messages.xml
<?xml version="1.0"?>
<!-- Global messages displayed in the back office -->
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mapixcms.org/schemas/messages.xsd">
	<message id="admin" lang="en">Administration site</message>
	<message id="admin" lang="fr">Site d'administration</message>
	<message id="core" lang="en">Core</message>
	<message id="core" lang="fr">Noyau</message>
	<message id="version" lang="en">Version</message>
	<message id="version" lang="fr">Version</message>
	<message id="noscript" lang="en">Config Error : Mapix CMS back office requires a Javascript enabled browser.</message>
	<message id="noscript" lang="fr">Erreur de configuration : Le site d'administration de Mapix CMS nécéssite un navigateur web avec la fonction Javascript activée.</message>
	<message id="location" lang="en">Location</message>
	<message id="location" lang="fr">Emplacement</message>
	<message id="backupBeforeModify" lang="en">Backup this file before modifying</message>
	<message id="backupBeforeModify" lang="fr">Sauvegarder ce fichier avant d'enregistrer</message>
	<message id="cancel" lang="en">Cancel</message>
	<message id="cancel" lang="fr">Annuler</message>
	<message id="submit" lang="en">Submit</message>
	<message id="submit" lang="fr">Envoyer</message>
	<message id="user" lang="en">User</message>
	<message id="user" lang="fr">Utilisateur</message>
	<message id="group" lang="en">Group</message>
	<message id="group" lang="fr">Groupe</message>
	<message id="refresh" lang="en">Refresh</message>
	<message id="refresh" lang="fr">Actualiser</message>
	<message id="action" lang="en">Action</message>
	<message id="action" lang="fr">Action</message>
	<message id="userError" lang="en">User must be identified to access this service.</message>
	<message id="userError" lang="fr">Vous devez être identifié pour accéder à ce service.</message>
	<message id="file" lang="en">File </message>
	<message id="file" lang="fr">Le fichier </message>
	<message id="backedUpAndModified" lang="en">backed up and modified</message>
	<message id="backedUpAndModified" lang="fr">sauvegardé et modifié</message>	
	<message id="modified" lang="en">modified</message>
	<message id="modified" lang="fr">modifié</message>
	<message id="wasSuccessfully" lang="en"> was successfully </message>
	<message id="wasSuccessfully" lang="fr"> a été </message>
	<message id="couldNotBe" lang="en"> could not be </message>
	<message id="couldNotBe" lang="fr"> n'a pas pu être </message>
	<message id="lockError" lang="en">This file is locked, you can't modify it.</message>
	<message id="lockError" lang="fr">Ce fichier est verrouillé, vous ne pouvez pas le modifier.</message>
	<message id="locked" lang="en">locked</message>
	<message id="locked" lang="fr">verrouillé</message>
	<message id="unlocked" lang="en">unlocked</message>
	<message id="unlocked" lang="fr">déverrouillé</message>
	<message id="emptyFileError" lang="en">No file is opened in this editor. Go back to the folder editor and select a file to edit.</message>
	<message id="emptyFileError" lang="fr">Aucun fichier n'est ouvert dans cet éditeur. Retournez à l'explorateur pour sélectionner un fichier à éditer.</message>
	<message id="close" lang="en">Close</message>
	<message id="close" lang="fr">Fermer</message>
	<message id="save" lang="en">Modify</message>
	<message id="save" lang="fr">Enregistrer</message>
	<message id="saveAndClose" lang="en">Modify and close</message>
	<message id="saveAndClose" lang="fr">Enregistrer et fermer</message>
</messages>

=== ircf/mapix/mapix/user/messages.xml
<?xml version="1.0"?>
<!-- Global messages displayed in the back office -->
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mapixcms.org/schemas/messages.xsd">
	<!-- Login -->	
	<message id="loginTitle" lang="en">Please login to access the administration service</message>
	<message id="loginTitle" lang="fr">Identifiez-vous pour accéder au site d'administration</message>
	<message id="loginText" lang="en">This service is restricted to identified users. You can use one of the following user accounts : (admin,demo) , (editor,demo) or (designer,demo).</message>
	<message id="loginText" lang="fr">Ce service est réservé aux utilisateurs identifiés. Vous pouvez utiliser un des comptes utilisateurs suivants : (admin,demo) , (editor,demo) ou (designer,demo).</message>	
	<message id="login" lang="en">Login</message>
	<message id="login" lang="fr">Utilisateur</message>
	<message id="password" lang="en">Password</message>
	<message id="password" lang="fr">Mot de passe</message>
	<message id="loginSubmit" lang="en">Login</message>
	<message id="loginSubmit" lang="fr">Connexion</message>
	<message id="loginFailed" lang="en">Sorry, login and/or password are invalid.</message>
	<message id="loginFailed" lang="fr">Désolé, le nom d'utilisateur et/ou le mot de passe que vous avez saisi est invalide.</message>
	<message id="logout" lang="en">Logout</message>
	<message id="logout" lang="fr">Déconnexion</message>
	<!-- OpenID Login -->
	<message id="openIdTitle" lang="en">Login using your OpenID account</message>
	<message id="openIdTitle" lang="fr">Identifiez-vous avec OpenID</message>
	<message id="openIdText" lang="en">If you have a Mapix user account related to an OpenID account, you can use it to login. You can use (demo.mapixcms.myopenid.com,demo) to login the admin user account.</message>
	<message id="openIdText" lang="fr">Si votre compte utilisateur Mapix est relié à un identifiant OpenID, vous pouvez l'utiliser pour vous connecter. Vous pouvez utiliser (demo.mapixcms.myopenid.com,demo) pour accéder au compte administrateur.</message>
	<message id="openIdLogin" lang="en">OpenID Login</message>
	<message id="openIdLogin" lang="fr">Identifiant OpenID</message>
</messages>

=== ircf/mapix/mapix/package/messages.xml
<?xml version="1.0"?>
<!-- Global messages displayed in the back office -->
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mapixcms.org/schemas/messages.xsd">
	<!-- Package manager -->
	<message id="packageManager" lang="en">Package manager</message>
	<message id="packageManager" lang="fr">Gestionnaire de paquets</message>
	<message id="packageServerUpdateError" lang="en">Could not connect to the Mapix CMS package repository. Check the package manager configuration in the /admin/index.map file or try to connect later.</message>
	<message id="packageServerUpdateError" lang="fr">Impossible de se connecter au dépôt de paquets Mapix CMS. Vérifiez la configuration du gestionnaire de paquets dans le fichier /admin/index.map ou réessayez plus tard.</message>
	<message id="packageUpdateError" lang="en">Could not read your local package configuration. One or many package descriptor are not XML documents.</message>
	<message id="packageUpdateError" lang="fr">Impossible de lire votre configuration de paquets. Un ou plusieurs descripteurs ne sont pas des documents XML.</message>
	<message id="packageInstalled" lang="en">Package(s) installed or upgraded successfully.</message>
	<message id="packageInstalled" lang="fr">Paquet(s) installé(s) ou mis à jour avec succès.</message>
	<message id="packageInstallError" lang="en">One ore many packages could not be installed or upgraded. Ensure that the package install folder is writable or try again later.</message>
	<message id="packageInstallError" lang="fr">Un ou plusieurs paquets n'ont pas pu être installés ou mis à jour. Assurez-vous que le dossier d'installation des paquets soit accessible en écriture ou réessayez plus tard.</message>
	<message id="packageUninstalled" lang="en">Package(s) uninstalled successfully.</message>
	<message id="packageUninstalled" lang="fr">Paquet(s) désinstallé(s) avec succès.</message>
	<message id="packageUninstallError" lang="en">One or many packages could not be uninstalled. Ensure your install folder is writable and try again.</message>
	<message id="packageUninstallError" lang="fr">Un ou plusieurs paquets n'ont pas pu être désinstallés. Assurez-vous que le dossier d'installation des paquets soit accessible en écriture et réessayez.</message>
	<message id="dataDownloaded" lang="en">KB will be downloaded from the repository and installed on the server.</message>
	<message id="dataDownloaded" lang="fr">Ko seront téléchargés depuis le dépôt et installés sur le serveur.</message>
	<message id="dataRemoved" lang="en">Ko will be removed from the server.</message>
	<message id="dataRemoved" lang="fr">Ko seront supprimés du serveur.</message>
	<message id="packageSubmit" lang="en">This operation might take a moment and should not be interrupted. Are you sure ?</message>
	<message id="packageSubmit" lang="fr">Cette opération peut prendre un certain temps et ne doit pas être interrompue. Etes-vous sûr ?</message>
	<message id="size" lang="en">Size</message>
	<message id="size" lang="fr">Taille</message>
	<message id="upgrade" lang="en">Upgrade</message>
	<message id="upgrade" lang="fr">Mettre à jour</message>
	<message id="install" lang="en">Install</message>
	<message id="install" lang="fr">Installer</message>
	<message id="uninstall" lang="en">Uninstall</message>
	<message id="uninstall" lang="fr">Désinstaller</message>
	<message id="show" lang="en">Show</message>
	<message id="show" lang="fr">Afficher</message>
	<message id="installedPackages" lang="en">Installed packages</message>
	<message id="installedPackages" lang="fr">Paquets installés</message>
	<message id="upgrades" lang="en">Upgrades</message>
	<message id="upgrades" lang="fr">Mises à jour</message>
	<message id="allPackages" lang="en">All packages</message>
	<message id="allPackages" lang="fr">Tous les paquets</message>
	<message id="repository" lang="en">Repository</message>
	<message id="repository" lang="fr">Dépôt</message>
	<message id="packageList" lang="en">Package list</message>
	<message id="packageList" lang="fr">Liste des paquets</message>
	<message id="installedIn" lang="en">installed in</message>
	<message id="installedIn" lang="fr">installé dans</message>
</messages>

=== ircf/mapix/mapix/xml/messages.xml
<?xml version="1.0"?>
<!-- Global messages displayed in the back office -->
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mapixcms.org/schemas/messages.xsd">
	<!-- Xml editor -->	
	<message id="xmlEditor" lang="en">XML document editor</message>
	<message id="xmlEditor" lang="fr">Editeur de documents XML</message>
	<message id="addNode" lang="en">Add node</message>
	<message id="addNode" lang="fr">Ajouter un élément</message>
	<message id="nodeName" lang="en">Node name</message>
	<message id="nodeName" lang="fr">Nom</message>
	<message id="nodePosition" lang="en">Node position</message>
	<message id="nodePosition" lang="fr">Position</message>
	<message id="beforeCurrentNode" lang="en">Before current node</message>
	<message id="beforeCurrentNode" lang="fr">Avant l'élément courant</message>
	<message id="afterCurrentNode" lang="en">After current node</message>
	<message id="afterCurrentNode" lang="fr">Après l'élément courant</message>
	<message id="intoCurrentNode" lang="en">Into current node</message>
	<message id="intoCurrentNode" lang="fr">Dans l'élément courant</message>
	<message id="removeNode" lang="en">Remove node</message>
	<message id="removeNode" lang="fr">Supprimer cet élément</message>
	<message id="removeNodeConfirm" lang="en">Are you sure you want to remove this node ?</message>
	<message id="removeNodeConfirm" lang="fr">Etes-vous sûr de vouloir supprimer cet élément ?</message>
	<message id="foldUnfold" lang="en">Fold/Unfold</message>
	<message id="foldUnfold" lang="fr">Replier/déplier</message>
	<message id="foldUnfoldAll" lang="en">Fold/Unfold All</message>
	<message id="foldUnfoldAll" lang="fr">Tout replier/déplier</message>
	<message id="languageFilter" lang="en">Language filter</message>
	<message id="languageFilter" lang="fr">Filtrer les langues</message>
	<message id="xmlFileError" lang="en">This file is not a valid XML document. Try to open it with the text editor.</message>
	<message id="xmlFileError" lang="fr">Ce fichier n'est pas un document XML. Essayez de l'ouvrir avec l'éditeur texte.</message>
	<message id="schemaFileError" lang="en">This XML document is linked to an invalid schema. You should fix this using the text editor.</message>
	<message id="schemaFileError" lang="fr">Ce document XML est relié à un schéma invalide. Vous devriez corriger ce problème avec l'éditeur texte.</message>
	<message id="edit" lang="en">Edit</message>	
	<message id="edit" lang="fr">Editer</message>	
</messages>

=== ircf/mapix/mapix/image/messages.xml
<?xml version="1.0"?>
<!-- Image editor messages -->
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mapixcms.org/schemas/messages.xsd">
	<message id="imageEditor" lang="en">Image editor</message>
	<message id="imageEditor" lang="fr">Editeur d'images</message>
	<message id="rotateImage" lang="en">Rotate image</message>
	<message id="rotateImage" lang="fr">Pivoter l'image</message>
	<message id="cropImage" lang="en">Crop image</message>
	<message id="cropImage" lang="fr">Recadrer l'image</message>
	<message id="left" lang="en">Left</message>
	<message id="left" lang="fr">Gauche</message>
	<message id="top" lang="en">Top</message>
	<message id="top" lang="fr">Haut</message>
	<message id="width" lang="en">Width</message>
	<message id="width" lang="fr">Largeur</message>
	<message id="height" lang="en">Height</message>
	<message id="height" lang="fr">Hauteur</message>
	<message id="resizeImage" lang="en">Resize image</message>
	<message id="resizeImage" lang="fr">Redimensionner l'image</message>
	<message id="imageFileError" lang="en">This file is not a valid image. Try to open it with the text editor.</message>
	<message id="imageFileError" lang="fr">Ce fichier n'est pas une image. Essayez de l'ouvrir avec l'Ã©diteur texte.</message>
</messages>
